"""Added 

Revision ID: d230b433b514
Revises: fc10cf495e96
Create Date: 2023-12-27 00:37:08.191062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd230b433b514'
down_revision = 'fc10cf495e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
