"""Create initial tables

Revision ID: fc10cf495e96
Revises: 5cb2feee6bfa
Create Date: 2023-12-27 00:01:46.494696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc10cf495e96'
down_revision = '5cb2feee6bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
